### ISSUE TITLE
Can't find Python

### ISSUE THREAD

**Issue by jacebenson** [AvianFlu/node-waitpid#5]
When I installed this I got an error saying 'Error: Can't Find Python executable "python", you can ...'

![screenshot-2013-oct-16-129-pm](https://f.cloud.github.com/assets/638764/1345517/ef90bafa-3690-11e3-8953-c93702355e03.png)

**Comment by mmalecki** [comment]
@jacebenson you need Python in order to build Node extensions, and it's very unlikely that this library will ever work on Windows.

However, Node just added `child_process.execSync`, and you should be using that instead.
